### ISSUE TITLE
Problems building a 3D hypercube when selecting multiple variables

### ISSUE THREAD

**Issue by mariahpope** [ecmwf/anemoi-datasets#155]
**Describe the bug**
I am trying to build a dataset and am running into a bug while the module tries to build a 3D hypercube. This only happens when there is more than one variable.

** Version number **
The most current version of the develop branch and pyproject.toml (as of Dec 3rd, 2024)

**To Reproduce**
1. Used a yaml with this configuration:
```
dates:
  start: 2021-01-01T00:00:00
  end: 2021-01-01T23:00:00
  frequency: 6h

input:
    xarray-zarr:
        url: "gs://gcp-public-data-arco-era5/ar/1959-2022-6h-128x64_equiangular_conservative.zarr"
        param:
            - 2m_temperature
            - surface_pressure
```
2. Ran:
`anemoi-datasets create era5_test.yaml era5_test.zarr`

**URL to sample input data**
gs://gcp-public-data-arco-era5/ar/1959-2022-6h-128x64_equiangular_conservative.zarr

**Expected behavior**
This should have created a dataset with both 2m_temperature and surface_pressure, but it results in a hypercube error (see screenshot below). If I switch to only one variable (e.g. just 2m_temperature) it works just fine.

**Screenshots**
<img width="1064" alt="Screenshot 2024-12-03 at 1 45 55 PM" src="https://github.com/user-attachments/assets/1221dc68-be57-4912-9387-fe920349deab">

**Comment by b8raoult** [comment]
Can you try https://github.com/ecmwf/anemoi-datasets/pull/159 ?

**Comment by mariahpope** [comment]
Yes, just tried it! It seems to work now for the example I initially provided above (the era5 zarr with temperature and pressure)!
However, I did a few more tests out of curiosity and found that it will provide the same error if I try to add variables with additional levels. For example, if I use this yaml (same data, just add temperature levels 50 and 100):
```
dates:
  start: 2021-01-01T00:00:00
  end: 2021-01-01T23:00:00
  frequency: 6h

input:
  join:
  - xarray-zarr:
        url: "gs://gcp-public-data-arco-era5/ar/1959-2022-6h-128x64_equiangular_conservative.zarr"
        param:
            - 2m_temperature
            - surface_pressure
  - xarray-zarr:
        url: "gs://gcp-public-data-arco-era5/ar/1959-2022-6h-128x64_equiangular_conservative.zarr"
        param:
            - temperature
        level:
            - 50
            - 100
```
I get this similar error:
<img width="1070" alt="Screenshot 2024-12-13 at 10 55 11 AM" src="https://github.com/user-attachments/assets/bcecab12-641e-49f5-bde9-38f6880ad97a" />

If I just do level of 50 it works fine, but once I add another level (100) it produces that same error.

Thank you so much for looking into this!!
