### ISSUE TITLE
Computed forcings do not inherit coordinates from template if they were provided from external source

### ISSUE THREAD

**Issue by frazane** [ecmwf/anemoi-datasets#232]
**Describe the bug**
I am trying to build a dataset for the ICON-CH1 model data, starting from GRIB files. The model uses an unstructured grid, meaning that latitudes and longitudes cannot be decoded from the GRIB messages and must be provided explicitly from an external source. 

The issue is that when forcings must be computed, coordinates are not found anymore. See logs attached.

**Version number**

anemoi-datasets           0.5.17.dev13+g2983cc3.d2025030
anemoi-registry           0.1.7
anemoi-transform          0.1.3.dev13+g42e874b           
anemoi-utils              0.4.11         

**To Reproduce**
My config looks like this 

```yaml
input:
  join:
    - pipe:
      - grib:
          path: /path/to/grib/files
          param: [T, U]
          level: [60, 61]
          longitudes:
            path: /path/to/grid/file.nc
            param: "clon"
          latitudes:
            path: /path/to/grid/file.nc
            param: "clat"
            

      - rename: 
          param: {T: t, U: u}
            
    - forcings:
        template: ${input.join.0.pipe.0.grib}
        param:
          - cos_latitude
          - cos_longitude
          - sin_latitude
          - sin_longitude
          - cos_julian_day
          - sin_julian_day
          - cos_local_time
          - sin_local_time
          - insolation
 
```

**Additional context**
[coordinates_forcings_logs.txt](https://github.com/user-attachments/files/19270805/coordinates_forcings_logs.txt)
