### ISSUE TITLE
xarray-zarr data source workflow is currently broken

### ISSUE THREAD

**Issue by timothyas** [ecmwf/anemoi-datasets#248]
## Describe the bug

The xarray-zarr workflow is currently broken. I've tested various commits and it seems like the last working commit is 4abd0cc, and somewhere 2983cc3 broke the xarray-zarr workflow.

## Version number 

Commits 4abd0cc and 2983cc3

## To Reproduce

1. Get some template data and recipe file e.g. same as in #245 

  <details>
  <summary>pull_data.py</summary>

  ```python
  import xarray as xr
  import numpy as np
  
  import pooch # needed for tutorial dataset

  if __name__ == "__main__":

      ds = xr.tutorial.load_dataset("air_temperature")

      ds = ds.rename({"lat": "latitude", "lon": "longitude"})
      lonlat = ds.air.transpose("time", "longitude", "latitude")
      lonlat.to_dataset(name="temperature").to_zarr("lonlat.zarr")
  ```
  </details>

  <details>
  <summary>recipe.lonlat.yaml</summary>
 
  ```yaml
  dates:
    start: 2013-01-01T00:00:00
    end: 2013-01-04T18:00:00
    frequency: 6h

  input:
    join:
        - xarray-zarr:
            url: "lonlat.zarr"
            param:
                - temperature

        - forcings:
            template: ${input.join.0.xarray-zarr}
            param:
              - cos_latitude
              - cos_longitude
  ```
  </details>

2. Run it with the last working commit
  ```
  git checkout 4abd0cc
  anemoi-datasets create recipe.lonlat.yaml tester.zarr --overwrite
  ```

3. Then it will break with this commit

  ```
  git checkout 2983cc3
  anemoi-datasets create recipe.lonlat.yaml tester.zarr --overwrite
  ```

## Expected behavior

It should work as in step 2.

## Screenshots

Here's the error I'm seeing

![Image](https://github.com/user-attachments/assets/20d1fd43-8994-46d9-a7b5-5a3b337ea916)

**Additional context**

**Comment by b8raoult** [comment]
Do you have a simple recipe you can share?

**Comment by timothyas** [comment]
Hi @b8raoult, did you see the recipe I shared in the original issue? I made it so you have to click an arrow to expand and see the contents. In any case, here is a python script which will give you a small test dataset

```python
import xarray as xr
import numpy as np

import pooch # needed for tutorial dataset

if __name__ == "__main__":

    ds = xr.tutorial.load_dataset("air_temperature")

    ds = ds.rename({"lat": "latitude", "lon": "longitude"})
    lonlat = ds.air.transpose("time", "longitude", "latitude")
    lonlat.to_dataset(name="temperature").to_zarr("lonlat.zarr")
```

and here is the yaml recipe file
```yaml
dates:
  start: 2013-01-01T00:00:00
  end: 2013-01-04T18:00:00
  frequency: 6h

input:
  join:
      - xarray-zarr:
          url: "lonlat.zarr"
          param:
              - temperature

      - forcings:
          template: ${input.join.0.xarray-zarr}
          param:
            - cos_latitude
            - cos_longitude    
```

but I've noticed that using any xarray-zarr source is broken (or at least it was when I raised this issue) so any source should reproduce the issue
