### ISSUE TITLE
Forcings broken ?

### ISSUE THREAD

**Issue by flyIchtus** [ecmwf/anemoi-datasets#262]
**Describe the bug**
Many errors when prescribing forcings with grib sources

** Version number **
I am using the following versions/branche/sha1 of the anemoi packages
(alternatively the output of `pip freeze`)

https://github.com/ecmwf/anemoi-datasets.git@f30efd1c3cba39cca191246845e8dbd096328f2d

**To Reproduce**
1. `anemoi-datasets init aromeforcings.yaml aroforcings.zarr` in a relevant environment
2. Config file `aromeforcings.yaml`:
```
dates:
  start: 2023-05-20T00:00:00Z
  end: 2023-05-23T00:00:00Z
  frequency: 12h
input:
  join:
     - pipe:
        - grib:
            path: /ec/res4/scratch/fra3425/Titan/five-days-sample/{date:strftime(%Y-%m-%d)}/{date:strftime(%Y-%m-%d_%Hh%M)}/PAAROME_1S40_ECH0_ISOBARE.grib
            param: [u,v,t]
            levtype: pl
            level: [200]
        - remove_nans: {}
     - forcings:
        template: ${input.join.0.pipe.1}
        param:
        - cos_julian_day
        - sin_julian_day
        - cos_local_time
        - sin_local_time
        - cos_latitude
        - sin_latitude
        - cos_longitude
        - sin_longitude
        - insolation
```
3. See error
The previous command was running smoothly up to now.
Two errors appear (second one after fixing the first):
(in earthkit-data)
`AttributeError: 'GroupOfDates' object has no attribute 'to_datetime_list'`

This one error shows that the forcings source of `anemoi` provides a `GroupOfDates` object to earthkit-data, while it should be providing a list of dates. The fix is quite easy.

`AssertionError: ${input.join.0.pipe.0} (type 'str') is not a proper source or dataset`
Meaning the `${input.join.0.pipe.0}` template is not properly decoded.

**URL to sample input data**
Provide a URL to a sample input data, or attach a file to that report if it is small enough.

**Expected behavior**
No error is supposed to show up, and dataset should init normally.

**Screenshots**

**Additional context**
This happens after a significant refactoring when some holes might have appeared.

Attempt of solving in #261
