### ISSUE TITLE
Static variables are ignored, at least in xarray-zarr workflow

### ISSUE THREAD

**Issue by timothyas** [ecmwf/anemoi-datasets#264]
### Describe the bug

When there are variables in the original dataset that do not vary with time, they are ignored.

### Version number

Commit 4abd0cc

### To Reproduce

1. Use this recipe to create a dataset:
  ```yaml
  # recipe.era5.yaml
  dates:
    start: 2000-01-01T00:00:00
    end: 2000-01-02T18:00:00
    frequency: 6h

  input:
    join:
        - xarray-zarr:
            url: "gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr"
            param:
              - land_sea_mask
              - 2m_temperature
  
        - xarray-zarr:
            url: "gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr"
            param:
              - temperature
            level:
              - 100
              - 500
              - 1000  
  ```

  ```
  anemoi-datasets create recipe.era5.yaml era5.anemoi.yaml
  ```

2. Visualize the original dataset, showing the dimensions of each data_var

![Image](https://github.com/user-attachments/assets/5f0cd06c-590d-4967-a26a-b30af5d2d6ff)

3. `land_sea_mask` is not in the variable list

![Image](https://github.com/user-attachments/assets/bf35aef9-b5f4-4d29-9300-74f3488c4b20)

### Expected behavior

I would expect `land_sea_mask` to be in the dataset, but I'm not sure if the behavior is just different from what I'm expecting. How does anemoi-datasets handle static variables?

**Comment by aperaza-bsc** [comment]
To build on top of this and add relevancy to this issue, I am facing the same problem with data coming from Destination Earth simulations.

**Comment by timothyas** [comment]
Thanks @aperaza-bsc! I would be interested to see what you did. Did you change the data source, or a configuration with anemoi-datasets to get it to work?

**Comment by aperaza-bsc** [comment]
Hi @timothyas! 

Yesterday I learnt much more about creating anemoi datasets and I was testing with different configurations and at one point I removed the constant and ocean fields as I had them in a different frequency than the rest. Then I forgot about it and thought I was having the same problem you were facing here 😅 
So I won't go into details there to create further confusion. On the other hand, if you were interested in our pipeline, we could discuss further but it's not the scope of this issue.

The good part is that I also found out why you were facing errors with the land_sea_mask of arco-era5. That does is timeless in the dataset, which makes sense but I also assumed it was repeated over time. Here is the output of accessing the DataArray of the land sea mask:

```py
>>> import xarray as xr
>>> xr.open_zarr("gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr").land_sea_mask
<xarray.DataArray 'land_sea_mask' (longitude: 64, latitude: 32)> Size: 8kB
dask.array<open_dataset-land_sea_mask, shape=(64, 32), dtype=float32, chunksize=(64, 32), chunktype=numpy.ndarray>
Coordinates:
  * latitude   (latitude) float64 256B -87.19 -81.56 -75.94 ... 81.56 87.19
  * longitude  (longitude) float64 512B 0.0 5.625 11.25 ... 343.1 348.8 354.4
Attributes:
    long_name:      Land-sea mask
    short_name:     lsm
    standard_name:  land_binary_mask
    units:          (0 - 1)
``` 

Then if you incorporate an additional source to the join operation from the example above with `repeated-dates` on `mode: constant` solves the problem of `land_sea_mask` not appearing in the dataset.

```
dates:
  start: 2000-01-01T00:00:00
  end: 2000-01-02T18:00:00
  frequency: 6h

input:
  join:
      - xarray-zarr:
          url: "gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr"
          param:
            - 2m_temperature
      - repeated_dates:
        mode: constant
        source:
          xarray-zarr:
            url: "gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr"
            param: 
              - land_sea_mask

      - xarray-zarr:
          url: "gs://weatherbench2/datasets/era5/1959-2023_01_10-6h-64x32_equiangular_conservative.zarr"
          param:
            - temperature
          level:
            - 100
            - 500
            - 1000  
```
