### ISSUE TITLE
Clarify the requirements and specifications for the expected metadata when creating anemoi datasets from xarray-zarr sources

### ISSUE THREAD

**Issue by aperaza-bsc** [ecmwf/anemoi-datasets#291]
**Describe the bug**

I will summarize two bugs that I have faced creating anemoi-datasets. 

Error 1: 
Input xarray-zarr with `forecast_reference_time` as name for the time dimension
`ValueError: Dimension name forecast_reference_time not supported`

Error 2:
As a follow-up of Error 1, this is what happens if only I rename  forecast_reference_time to time keeping its attributes
`NotImplementedError: len(date_coordinate)=1 len(time_coordinate)=0 len(step_coordinate)=0`

After these two errors, I have found no problem in creating the anemoi dataset with a attributeless time dimension. I also noticed that the arco-era5 google cloud dataset does the same.

** Version number **
I am using the following versions of the anemoi packages:

```
Singularity> pip list | grep anemoi
anemoi-datasets           0.5.16
anemoi-transform          0.1.3
anemoi-utils              0.4.12
```

**Additional context**

For now I have not shared reproducible examples of each bug as I already solved each of them and my intention for this issue is not to solve these bugs but to have more clarity on the structure of the data and its metadata used to create anemoi datasets.

**Comment by anaprietonem** [comment]
Hello @aperaza-bsc thanks for the issue! you can find some documentation for the Dataset API here https://anemoi.readthedocs.io/projects/datasets/en/latest/modules/dataset.html#anemoi.datasets.data.dataset.Dataset.frequency. The errors you mentioned are those because you were trying to build an anemoi-dataset from an xarray dataset? You can also found an example recipe https://anemoi.readthedocs.io/projects/datasets/en/latest/usage/getting_started.html that gets some data from the CDS that could be helpful if you get a view on the config definition and the workflow to create a dataset

**Comment by aperaza-bsc** [comment]
Hi @anaprietonem, thanks a lot for answering too!

I will have a better look at the Dataset API docs but my problem.

> The errors you mentioned are those because you were trying to build an anemoi-dataset from an xarray dataset?   

I am creating the anemoi-dataset from xarray-Zarr that are stored in disk. For context, I am using DestinationEarth outputs to create the anemoi-dataset. The current pipeline is FDB -> earthkitdata object -> Interpolate with earthkit regrid -> To xarray -> Write to Zarr -> Create the anemoi-dataset from the xarray-Zarr.

So I don't have any problem with creating the anemoi-dataset right now, but I have faced multiple problems related to the metadata of the xarray-Zarr datasets and what I wanted in terms of documentation is to know which metadata anemo-datasets create expects in a xarray-Zarr source

**Comment by anaprietonem** [comment]
Hello @aperaza-bsc ! thanks for the context. We don't have that requirements defined right now as it depends a bit on the dataset but appreciate is an area where we need to do better. Would you have a sample file of the zarr you generated with xarray you could share? or xarray to netcdf?

**Comment by aperaza-bsc** [comment]
Hi @anaprietonem

I was able to create a reproducible example of one of the errors I faced when creating datasets without strictly following the cf-conventions. This error appears when the pressure levels are not ordered ascendingly and instead descendingly.

To reproduce this error, I created a python script that creates two Zarrs from `arco-era5`, one with the pressure levels ordered ascendingly and the other descendingly. Then I created two configs for anemoi-datasets. 

As a follow-up I would be interested in creating a PR with assertions to check if the cf-conventions are being followed. Could you guide on how to do so correctly?

## Reproduce the error

### Anemoi-datasets version
anemoi-datasets           0.5.16

### Steps to reproduce
`>>> python reproduce.py`
`anemoi-datasets create arco_works.yaml test-arco.zarr` 
`anemoi-datasets create arco_reversed_pl.yaml test-arco-fail.zarr` 

### Files required
`reproduce.py`
```py
import xarray as xr
import numpy as np

ds = xr.open_zarr(
    'gs://gcp-public-data-arco-era5/ar/full_37-1h-0p25deg-chunk-1.zarr-v3',
    chunks=None,
    storage_options=dict(token='anon'),
)

ds_reversed = ds.reindex({"level": sorted(ds.level, reverse=True)})

ds = ds.sel(time="2020-01-01")
ds = ds[["temperature", "2m_temperature"]]
ds.rename({"latitude":"lat", "longitude":"lon"})
ds.to_zarr("arco-era5-test.zarr", mode="w")


ds_reversed = ds_reversed.sel(time="2020-01-01")
ds_reversed = ds_reversed[["temperature", "2m_temperature"]]
ds_reversed.rename({"latitude":"lat", "longitude":"lon"})
ds_reversed.to_zarr("arco-era5-test-reversed.zarr", mode="w")
``` 

`arco_works.yaml`
```YAML
dates:
  start: 2020-01-01T00:00:00
  end: 2020-01-01T23:00:00
  frequency: 6h

input:
  join:
      - xarray-zarr:
          url: "arco-era5-test.zarr"
          param:
              - 2m_temperature

      - xarray-zarr:
          url: "arco-era5-test.zarr"
          param:
              - temperature
          level:
              - 1000
              - 500
```
`arco_reversed_pl.yaml`
```YAML
dates:
  start: 2020-01-01T00:00:00
  end: 2020-01-01T23:00:00
  frequency: 6h

input:
  join:
      - xarray-zarr:
          url: "arco-era5-test-reversed.zarr"
          param:
              - 2m_temperature

      - xarray-zarr:
          url: "arco-era5-test-reversed.zarr"
          param:
              - temperature
          level:
              - 1000
              - 500
```
