### ISSUE TITLE
Unable to use `xarray-zarr` source to with GCP ARCO ERA5

### ISSUE THREAD

**Issue by veech** [ecmwf/anemoi-datasets#298]
I'm attempting to run the [example in the docs](https://anemoi.readthedocs.io/projects/datasets/en/latest/datasets/building/sources/xarray-zarr.html) to utilize the ARCO ERA5 dataset from the GCP bucket but I get this error:

```
anemoi/datasets/create/sources/xarray_zarr.py", line 41, in execute
    return load_many("🇿", context, url, *args, **kwargs).execute(dates)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: load_many() missing 1 required positional argument: 'pattern'
```

This is the YAML config I'm using:
```yaml
dates:
  start: 2021-01-01T00:00:00
  end: 2021-01-10T12:00:00
  frequency: 6h

input:
  join:
  - xarray-zarr:
      url: "gs://gcp-public-data-arco-era5/ar/1959-2022-6h-128x64_equiangular_conservative.zarr"
      param:
      - surface_pressure
      - 2m_temperature
      - 10m_u_component_of_wind
      - 10m_v_component_of_wind

  - xarray-zarr:
      url: "gs://gcp-public-data-arco-era5/ar/1959-2022-6h-128x64_equiangular_conservative.zarr"
      param:
      - temperature
      level:
      - 1000
      - 500
```

and the command I'm running:

```
$ anemoi-datasets create arco-era5.yaml ./arco-era5.zarr
```

Could I be doing something wrong?

### Version Info
`python 3.11.12`
`anemoi-datasets==0.5.21`
