### ISSUE TITLE
Ability to restrict area's using `xarray-zarr` source

### ISSUE THREAD

**Issue by veech** [ecmwf/anemoi-datasets#340]
I'm wondering if it's possible to create a dataset with a limited area region with the `xarray-zarr` source similar to how you'd do it using the `mars` source.

I tried doing:
```yaml
dates:
  start: 2020-01-01T00:00:00
  end: 2020-01-01T00:00:00
  frequency: 1h

input:
  join:
    - xarray-zarr:
        url: 'gs://gcp-public-data-arco-era5/ar/1959-2022-full_37-1h-0p25deg-chunk-1.zarr-v2'
        param:
          - u_component_of_wind
          - v_component_of_wind
          
        latitude: [24, 50]
        longitude: [235, 294]
        level:
          - 1000
        options:
          chunks: null
          storage_options:
            token: anon
```

But I get a bunch of errors. My current plan is to create a global region with this and then use the `anemoi-dataset` source to restrict the region.

```yaml
dates:
  start: 2020-01-01T00:00:00
  end: 2020-01-01T00:00:00
  frequency: 1h

input:
  anemoi-dataset:
    dataset: ./datasets/conus-era5.zarr
    area: [50, -125, 24, -66]
```

This works but I worry I'm overlooking something simple.
