### ISSUE TITLE
Variable naming when combining different level types in one dataset

### ISSUE THREAD

**Issue by mpartio** [ecmwf/anemoi-datasets#87]
**Describe the bug**

When combining surface level and pressure level data in a single dataset, the naming convention is param_level which is silly for certain surface level parameters that already have the level information in their name (for example 2t).

**To Reproduce**

```
dates:
  start: 2024-10-12T14:00:00Z
  end: 2024-10-12T14:00:00Z
  frequency: 1h
input:
  join:
  - grib:
      path: example.grib2
      param: [2t]
      levtype: sfc
  - grib:
      path: example.grib2
      param: [z]
      levtype: pl
      levelist: [1000]
```

```
$ anemoi-datasets create example.yaml example.zarr
```

```
$ anemoi-datasets inspect example.zarr
📦 Path          : example.zarr
🔢 Format version: 0.30.0

📅 Start      : 2024-10-12 14:00
📅 End        : 2024-10-12 14:00
⏰ Frequency  : 1h
🚫 Missing    : 0
🌎 Resolution : 2p5km
🌎 Field shape: [1069, 949]

📐 Shape      : 1 × 2 × 1 × 1,014,481 (7.7 MiB)
💽 Size       : 13.4 MiB (13.4 MiB)
📁 Files      : 75

   Index │ Variable │     Min │     Max │    Mean │   Stdev
   ──────┼──────────┼─────────┼─────────┼─────────┼────────
       0 │ 2t_2     │ 262.871 │ 289.308 │ 280.725 │ 3.92529
       1 │ z_1000   │ -2214.4 │ 1830.41 │ 485.131 │ 977.196
   ──────┴──────────┴─────────┴─────────┴─────────┴────────
🔋 Dataset ready, last update 3 hours ago.
📊 Statistics ready.


```

**URL to sample input data**

Attached to this issue ticket.

**Expected behavior**

surface level parameters are without level value, ie. "2t"
vertical levels (pressure, hybrid, whatever) are with level value, ie "z_1000"

**Additional context**

```
$ anemoi-datasets --version
0.5.7
```
I tried changing "variable_naming" in "build":

```
build:
    variable_naming: param
```

But this changed the naming for all sources -- I need to change the naming for just a single source.

**Comment by mpartio** [comment]
[example.grib2.gz](https://github.com/user-attachments/files/17363043/example.grib2.gz)

example data -- compressed with gzip because github did not allow uploading of grib.

**Comment by mchantry** [comment]
Hello
Thanks for raising this isssue, there is work in progress to better differentiate between different level types.
We will report back soon.

**Comment by mpartio** [comment]
Thanks!

I also found a small bug in the code that uses xarray for reading data (like netcdf source); do you prefer a pull request or some other means to deliver this information?

**Comment by mchantry** [comment]
PR would be great thanks.

**Comment by mchantry** [comment]
@mpartio You could look at https://anemoi-datasets.readthedocs.io/en/latest/building/filters/rename.html to rename `2t_2` to `2t`. Would this meet your needs?

**Comment by mpartio** [comment]
Thanks for the suggestion! I tried `rename` and I could not get it to work this way. My assumption is that anemoi is using naming scheme `{param}_{level}` and the rename is only affecting the `{param}` part.

For example this configuration:

```
  pipe:
    - join:
      - grib:
          path: example.grib2
          param: [2t]
          levtype: sfc
      - grib:
          path: example.grib2
          param: [z]
          levtype: pl
          levelist: [1000]
    - rename:
        param:
          2t_2: 2t
```

And inspecting the resulting zarr:

```
   Index │ Variable │     Min │     Max │    Mean │   Stdev
   ──────┼──────────┼─────────┼─────────┼─────────┼────────
       0 │ 2t_2     │ 262.871 │ 289.308 │ 280.725 │ 3.92529
```

If I change the rename to:

```
    - rename:
        param:
          2t: tempe
```

I get:

```
   Index │ Variable │     Min │     Max │    Mean │   Stdev
   ──────┼──────────┼─────────┼─────────┼─────────┼────────
       0 │ tempe_2  │ 262.871 │ 289.308 │ 280.725 │ 3.92529
```
